### ISSUE TITLE
prevent new game from starting until all tiles have been removed

### ISSUE THREAD

**Issue by aroman** [AEPi-AK/barnyard-server#12]
we may want a "GameWaitTileRemove" phase or something?

**Comment by jbrown215** [comment]
It can be game waiting still-- i will just reject "joins" until all tiles are removed.

**Comment by aroman** [comment]
perfect

**Comment by jbrown215** [comment]
if you want to display instructions to remove the tiles, you can just check if the game is waiting and slots are not all empty

**Comment by jbrown215** [comment]
(ill do this tonight after I finish #SetTheory)

**Comment by aroman** [comment]
perf, ty

**Comment by jbrown215** [comment]
addressed in b2356eb
