### ISSUE TITLE
please set a profile picture on your github account #angryReactJSOnly

### ISSUE THREAD

**Issue by aroman** [AEPi-AK/barnyard-server#2]

**Comment by jbrown215** [comment]
i did it

**Comment by aroman** [comment]
![o4xweqw](https://cloud.githubusercontent.com/assets/531504/25095230/cb898d12-2368-11e7-89b1-c02d91d19921.gif)

**Comment by jbrown215** [comment]
![http://gph.is/1IF8ykO](url)

**Comment by jbrown215** [comment]
pls my gifs arent special

**Comment by aroman** [comment]
you can just drag and drop them onto the comment field :^)

**Comment by jbrown215** [comment]
http://reddit.com/r/reactiongifs/comments/30j2d2/mrw_i_get_home_on_friday/

**Comment by jbrown215** [comment]
pls
you lie

**Comment by jbrown215** [comment]
![](http://i.imgur.com/Up9DEn0.gif)

**Comment by jbrown215** [comment]
i did it

**Comment by jbrown215** [comment]
now im going to delete the history of failure
